# Refer to https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# for the default rubocop configuration.

require:
  - rubocop/rspec/focused

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/schema.rb
    - db/fixtures/development/cooking_methods.rb
    - db/fixtures/development/main_ingredients.rb
    - db/fixtures/development/recipe_categories.rb
    - db/fixtures/development/special_occasions.rb
    - db/fixtures/development/states.rb
  Include:
    - '*.rake'
    - Capfile
    - Gemfile
    - Guardfile

Rails:
  Enabled: true

Rails/ActionFilter:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 4

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 89

Metrics/MethodLength:
  Max: 30

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  Enabled: false

RSpec/Focused:
  Enabled: true
